### ISSUE TITLE
[SUGGEST] 패키지 구조 수정

### ISSUE THREAD

**Issue by muncool39** [Trip-Record/Server#11]
## Description
현재 저희 패키지가 각 도메인 별로 나누어져 있는데, 
관계성이 깊은 도메인들은 같은 패키지로 묶고 엔티티나 서비스 등은 하위 패키지를 생성해 분리하는 것은 어떨까요?

아래는 예시입니다.

- 현재 구조
```
record
   ㄴrecord
   ㄴrecordService
recordLike
   ㄴrecordLike
   ㄴrecordLikeService
recordComment
   ㄴrecordComment
   ㄴrecordCommentService
```
- 제안 구조
```
record
   ㄴmodel
         ㄴrecord
         ㄴrecordLike
         ㄴrecordComment
   ㄴservice
         ㄴrecordService
         ㄴrecordLikeService
         ㄴrecordCommentService
```
규모가 작았다면 현재도 충분히 괜찮다고 생각하는데,
도메인이 많아짐에 따라 연관된 것들은 한번 묶어서 진행해도 괜찮다고 생각해 제안해봅니다!
편하게 의견 주세요 😃

**Comment by gitseoyeon** [comment]
네 저도 엔티티 서비스 레포지토리와 같은것들은 패키지로 분류하면 파일을 구별하는데 쉬울거라 생각해요! 좋은 제안 같습니다~~

**Comment by ChaeAg** [comment]
네 좋습니다~~ 찬성!

**Comment by muncool39** [comment]
확인했습니다~ 수정 후 이슈 연결해서 닫을게요!
