### ISSUE TITLE
[SUGGEST] 많이 사용되는 메서드 위치 관련

### ISSUE THREAD

**Issue by muncool39** [Trip-Record/Server#21]
## Description
현재 개발중에 작성한, id로 리소스를 찾고, 없다면 오류를 반환하는 코드입니다.
```java
private User getUserOrException(Long userId) {
    return userRepository.findById(userId).orElseThrow(() ->
            new TripRecordException(ErrorCode.USER_NOT_FOUND));
}
```

```java
private Place getPlaceOrException(Long placeId) {
    return placeRepository.findByPlaceId(placeId).orElseThrow(() ->
            new TripRecordException(ErrorCode.PLACE_NOT_FOUNT));
}
```

이렇게 "id를 받아서 해당 id와 일치하지 않으면 오류를 반환하는 로직"이 전체적으로 많이 사용되잖아요
일단 제가 맡은 서비스에 쓴 코드지만, 넓게 보면 User와 Place를 사용하는 모든 서비스에서 사용할 수 있잖아요?!

그래서 차라리 저 둘을 각자 UserService, PlaceService에 메서드로 만들어서 service.get~OrException으로 사용하면 어떨까
이런 생각이 들었는데, 또 내용이 수정될 일도 별로 없고 코드가 짧기도 하고 그냥 따로 하나씩 위치하는게 덜 복잡한가 생각도 들고 많이 고민이 되더라고요

그래서 이 부분은 어떻게 생각하시는지 같이 고민하고 의견 나누면 좋겠습니다...😅

**Comment by gitseoyeon** [comment]
아무래도 서비스 구현 할 때마다 id와 일치하는지 아닌지 작성하는 건 항상 작성하다보니 번거로움이 생길 거 같긴하네요!
따로 메서드를 만들어서 두면 사용할 때 편하고 코드도 길이도 짧아질거 같아 좋은 방법이라고 생각합니다!

**Comment by ChaeAg** [comment]
좋은 의견이네요!
같은 Service 레이어에서 여러번 수행되는 로직은 메서드로 따로 분리하는게 더 용이할 것 같네요!!
대표적으로 말씀해주신 ID로 조회하는 부분인 것 같아요.
따로 분리하는 것 찬성입니다!! 👍

**Comment by muncool39** [comment]
넵! 의견을 반영하는 방향으로 수정 진행하겠습니다~
