### ISSUE TITLE
[SUGGEST] 유저 기본 정보를 담을 DTO 구현 건

### ISSUE THREAD

**Issue by muncool39** [Trip-Record/Server#42]
## Description
채은님의 #39 를 보면서 든 생각입니다!
저희가 조회 API를 구현할 경우, 요구사항에 맞춰 사용자 정보를 함께 담아서 줘야 되잖아요?
- 기록
![image](https://github.com/Trip-Record/Server/assets/105481797/37675d4c-c657-4235-8b35-4933cdc32218)
- 댓글
![image](https://github.com/Trip-Record/Server/assets/105481797/f2db5ecf-48f8-444b-855d-0af6abcf1003)
- 일정
![image](https://github.com/Trip-Record/Server/assets/105481797/9e94a0bc-7873-40e1-ae82-e104df6ad4d3)

해당 기획 화면들을 보면 반환할 유저 정보가 동일한데,
UserProfile, UserBasicInfo 이런 식으로 DTO를 만들고, 각 응답에 해당 DTO를 포함시키는 형식으로 구현하는 것은 어떨까요?
편하게 의견 주세요 ! 😃

**Comment by gitseoyeon** [comment]
아 이슈로 자세히 설명해주시니까 더 이해가 가네요!! 저는 좋은 방법인 거 같습니다!

**Comment by ChaeAg** [comment]
오~ 저도 구현하면서 고민했던 부분인데, 요렇게 자주 동일한 양식이 쓰인다면 만드는게 훨씬 좋을 것 같아요!!! 
좋은 의견입니다 👍

**Comment by muncool39** [comment]
감사합니다 👍 이렇게 진행해보아요!
