### ISSUE TITLE
[FIX] 병합 과정에 생긴 오류 해결

### ISSUE THREAD

**Issue by ChaeAg** [Trip-Record/Server#45]
## Description
충돌 해결 과정에서 ScheduleService 내 import문 복구,
최신화 되어 있지 않은 엔티티 필드명 변경

## To-Do
- [x] 충돌 해결 과정에서 누락된 import문 복구
- [x] 최신화 되어 있지 않은 엔티티 필드명 변경

**Comment by muncool39** [comment]
핫픽스 확인했습니다! 👍
