### ISSUE TITLE
[FIX] 요구사항에 맞는 Spring Security 사용자 접근 권한 설정 추가

### ISSUE THREAD

**Issue by ChaeAg** [Trip-Record/Server#48]
## Description
기능 요구사항에 따르면 로그인 하지 않은 사용자가 접근 가능한 기능은 아래와 같음.
- 게시글 열람 (기록, 일정)
- 댓글 열람 (기록 댓글, 일정 댓글)
- 여행지 랭킹 확인

해당 기능의 API 경로로 오는 요청에 대한 인증, 인가는 수행하지 않도록 설정해야 함.

## To-Do
- [x] Spring Security 설정 파일 인증,인가 제외 경로 추가

**Comment by muncool39** [comment]
제안해주신 배열로 추가하는 방법, 정말 좋은 것 같습니다 !👍
