### ISSUE TITLE
[BUG] informations API 400 에러 

### ISSUE THREAD

**Issue by Goongam** [Trip-Record/Server#88]
## Description
- postman 요청
![image](https://github.com/Trip-Record/Server/assets/59019137/075b3e55-e1f0-4ff9-9927-a3a65e4a3954)

- 브라우저 요청
![image](https://github.com/Trip-Record/Server/assets/59019137/2afdb219-af94-4370-9770-9be0e0705437)

헤더에 토큰을 포함하지 않으면 401에러를 잘 받아오는데 
로그인 후 발급받은 Bearer 토큰과 함께 informations API요청 시 400에러와 함께 예기치 않은 에러메시지가 반환됩니다.
요청의 방식에 문제가 있는 것인지 단순 버그인지 확인해주시면 감사합니다!

**Comment by ChaeAg** [comment]
확인 감사드려요!!!
해당 API에 오류가 있어 해결한 적이 있는데, 변경사항이 서버에 반영되지 않아서 발생한 문제였습니다!
현재 서버에 변경사항 반영 완료되어, 해당 API 잘 작동됩니다!
불편 드려서 죄송해요 😓

**Comment by Goongam** [comment]
수정 확인  했습니다 감사합니다! 👍
